// <auto-generated /> DO NOT EDIT
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Contracts.Packet;

public static class WireJson
{
    public static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web)
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };
    public static string Serialize<T>(T v) => JsonSerializer.Serialize(v, Options);
    public static T? Deserialize<T>(string json) => JsonSerializer.Deserialize<T>(json, Options);
}

public sealed class RoomDto
{
  public string Id { get; set; } = string.Empty;
  public string Title { get; set; } = string.Empty;
  public string Map { get; set; } = string.Empty;
  public int Max { get; set; }
  public int Cur { get; set; }
  public string Status { get; set; } = string.Empty;
  public string Visibility { get; set; } = string.Empty;
  public long UpdatedAtMs { get; set; }
}
public sealed class CreateRoomReq
{
  public string Title { get; set; } = string.Empty;
  public string Map { get; set; } = string.Empty;
  public int Max { get; set; } = 2;
  public string Visibility { get; set; } = "Public";
}
public sealed class GetRoomsRes
{
  public List<RoomDto> Rooms { get; set; } = new List<RoomDto>();
  public string? NextCursor { get; set; } = string.Empty;
  public long ServerTimeMs { get; set; }
  public string Version { get; set; } = string.Empty;
}
public sealed class CreateRoomRes
{
  public string RoomId { get; set; } = string.Empty;
  public string WsUrl { get; set; } = string.Empty;
  public string Token { get; set; } = string.Empty;
}
public sealed class JoinRoomRes
{
  public string WsUrl { get; set; } = string.Empty;
  public string Token { get; set; } = string.Empty;
  public RoomDto Room { get; set; } = new RoomDto();
}
public sealed class ErrorRes
{
  public string Error { get; set; } = string.Empty;
  public string? Message { get; set; } = string.Empty;
  public string TraceId { get; set; } = string.Empty;
}
public sealed class MemberDto
{
  public string UserId { get; set; } = string.Empty;
  public string Name { get; set; } = string.Empty;
  public int Slot { get; set; }
  public bool Ready { get; set; }
}
public sealed class CountdownDto
{
  public int Seconds { get; set; }
  public long StartAtMs { get; set; }
}
public sealed class WelcomeState
{
  public RoomDto Room { get; set; } = new RoomDto();
  public List<MemberDto> Members { get; set; } = new List<MemberDto>();
  public CountdownDto? Countdown { get; set; }
}
public sealed class RoomPatch
{
  public int Cur { get; set; }
  public string Status { get; set; } = string.Empty;
  public long UpdatedAtMs { get; set; }
}
public sealed class UdpDto
{
  public string Host { get; set; } = string.Empty;
  public int Port { get; set; }
}
public sealed class OpOnly { public string Op { get; set; } = string.Empty; }
public sealed class HelloMsg
{
  public string Op { get; set; } = "hello";
  public string Token { get; set; } = string.Empty;
  public string Version { get; set; } = string.Empty;
}
public sealed class ReadyMsg
{
  public string Op { get; set; } = "ready";
  public bool Value { get; set; }
}
public sealed class LeaveMsg
{
  public string Op { get; set; } = "leave";
}
public sealed class WelcomeMsg
{
  public string Op { get; set; } = "welcome";
  public WelcomeState State { get; set; } = new WelcomeState();
}
public sealed class MemberJoinMsg
{
  public string Op { get; set; } = "member.join";
  public MemberDto Member { get; set; } = new MemberDto();
}
public sealed class MemberLeaveMsg
{
  public string Op { get; set; } = "member.leave";
  public string Id { get; set; } = string.Empty;
}
public sealed class MemberUpdateMsg
{
  public string Op { get; set; } = "member.update";
  public string Id { get; set; } = string.Empty;
  public bool Ready { get; set; }
}
public sealed class RoomUpdateMsg
{
  public string Op { get; set; } = "room.update";
  public RoomPatch Patch { get; set; } = new RoomPatch();
}
public sealed class CountdownStartMsg
{
  public string Op { get; set; } = "countdown.start";
  public int Seconds { get; set; }
  public long StartAtMs { get; set; }
}
public sealed class CountdownCancelMsg
{
  public string Op { get; set; } = "countdown.cancel";
}
public sealed class GameBeginMsg
{
  public string Op { get; set; } = "game.begin";
  public UdpDto Udp { get; set; } = new UdpDto();
  public string Ticket { get; set; } = string.Empty;
}
public sealed class WarnMsg
{
  public string Op { get; set; } = "warn";
  public string Code { get; set; } = string.Empty;
  public string? Target { get; set; } = string.Empty;
  public int? PerSec { get; set; }
}
