// Program.cs  (멀티 아웃풋 + 서버/유니티 이중 타깃 + 안정 초기화 + #nullable + block-scoped namespace)
// 예) dotnet run --project . -- "packets.yml" --server "..\Lobby\Domain\Contracts" --unity "..\..\Client\Assets\3.Script\NetWork\Common" --filename "Contracts.Generated.cs" --unity-mode jsonutility

#nullable enable
using System.Text;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

// ---------- 인자 파싱 ----------
var inPath = args.FirstOrDefault(a => !a.StartsWith("-")) ?? "packets.yml";
string? outSingle = ArgVal("--out");
string? outServer = ArgVal("--server");
string? outUnity = ArgVal("--unity");
string fileName = ArgVal("--filename") ?? "Contracts.Generated.cs";
string unityMode = ArgVal("--unity-mode") ?? "systemtextjson"; // "jsonutility" 권장(유니티 패키지 없즘)

string? ArgVal(string flag)
{
    // --flag value  또는  --flag=value 둘 다 지원
    for (int i = 0; i < args.Length; i++)
    {
        var a = args[i];
        if (a.Equals(flag, StringComparison.OrdinalIgnoreCase))
            return (i + 1 < args.Length) ? args[i + 1] : null;
        if (a.StartsWith(flag + "=", StringComparison.OrdinalIgnoreCase))
            return a[(flag.Length + 1)..].Trim('"');
    }
    return null;
}

// ---------- 스키마 로드 ----------
if (!File.Exists(inPath))
{
    Console.Error.WriteLine($"[ERR] schema not found: {Path.GetFullPath(inPath)}");
    return 1;
}

var deserializer = new DeserializerBuilder()
    .WithNamingConvention(UnderscoredNamingConvention.Instance)
    .IgnoreUnmatchedProperties()
    .Build();

var schemaText = File.ReadAllText(inPath, new UTF8Encoding(false));
var schema = deserializer.Deserialize<Schema>(schemaText);
var ns = string.IsNullOrWhiteSpace(schema.Namespace) ? "Contracts.Packet" : schema.Namespace!;

// ---------- 서버용 코드 (System.Text.Json + 프로퍼티 + block-scoped namespace) ----------
var serverSb = new StringBuilder();
serverSb.AppendLine("// <auto-generated /> DO NOT EDIT");
serverSb.AppendLine("#nullable enable");
serverSb.AppendLine("using System;");
serverSb.AppendLine("using System.Collections.Generic;");
serverSb.AppendLine("using System.Text.Json;");
serverSb.AppendLine("using System.Text.Json.Serialization;");
serverSb.AppendLine();
serverSb.AppendLine($"namespace {ns}");
serverSb.AppendLine("{");
EmitWireJson_Server(serverSb);
EmitHttpTypes_Server(serverSb, schema);
EmitWsTypes_Server(serverSb, schema);
EmitWsMessages_Server(serverSb, schema);
serverSb.AppendLine("}");

// ---------- 유니티용 코드 (JsonUtility + 필드(camelCase) + 배열 + block-scoped namespace) ----------
string? unityCs = null;
if (!string.IsNullOrWhiteSpace(outUnity))
{
    if (unityMode.Equals("jsonutility", StringComparison.OrdinalIgnoreCase))
    {
        var u = new StringBuilder();
        u.AppendLine("// <auto-generated /> DO NOT EDIT (UNITY)");
        u.AppendLine("using System;");
        u.AppendLine("using UnityEngine;");
        u.AppendLine();
        u.AppendLine($"namespace {ns}");
        u.AppendLine("{");
        EmitWireJson_Unity(u);
        EmitHttpTypes_Unity(u, schema);
        EmitWsTypes_Unity(u, schema);
        EmitWsMessages_Unity(u, schema);
        u.AppendLine("}");
        unityCs = u.ToString();
    }
    else
    {
        // Unity도 System.Text.Json을 그대로 쓸 경우(옵션)
        unityCs = serverSb.ToString();
    }
}

// ---------- 쓰기 ----------
var outTargets = new List<string>();
if (!string.IsNullOrWhiteSpace(outSingle)) outTargets.Add(outSingle!);
if (!string.IsNullOrWhiteSpace(outServer)) outTargets.Add(outServer!);
if (outTargets.Count == 0) outTargets.Add("./");

foreach (var dir in outTargets)
{
    var outDir = Path.GetFullPath(dir);
    Directory.CreateDirectory(outDir);
    var outPath = Path.Combine(outDir, fileName);
    File.WriteAllText(outPath, serverSb.ToString(), new UTF8Encoding(false));
    Console.WriteLine($"Generated: {outPath}");
}

if (!string.IsNullOrWhiteSpace(outUnity))
{
    var outDir = Path.GetFullPath(outUnity);
    Directory.CreateDirectory(outDir);
    var outPath = Path.Combine(outDir, fileName);
    File.WriteAllText(outPath, unityCs ?? serverSb.ToString(), new UTF8Encoding(false));
    Console.WriteLine($"Generated: {outPath}");
}

return 0;

// ===================== 서버 방출 (System.Text.Json + 프로퍼티) =====================

static void EmitWireJson_Server(StringBuilder sb)
{
    sb.AppendLine(@"
public static class WireJson
{
    public static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web)
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };
    public static string Serialize<T>(T v) => JsonSerializer.Serialize(v, Options);
    public static T? Deserialize<T>(string json) => JsonSerializer.Deserialize<T>(json, Options);
}
");
}

static void EmitHttpTypes_Server(StringBuilder sb, Schema s)
{
    if (s.Http?.Types is null) return;
    foreach (var (name, fields) in s.Http.Types)
        EmitServerClass(sb, name, fields);
}

static void EmitWsTypes_Server(StringBuilder sb, Schema s)
{
    if (s.Ws?.Types is null) return;
    foreach (var (name, fields) in s.Ws.Types)
        EmitServerClass(sb, name, fields);
}

static void EmitWsMessages_Server(StringBuilder sb, Schema s)
{
    sb.AppendLine("public sealed class OpOnly { public string Op { get; set; } = string.Empty; }");
    if (s.Ws?.C2s is not null)
        foreach (var m in s.Ws.C2s) EmitServerMessage(sb, m);
    if (s.Ws?.S2c is not null)
        foreach (var m in s.Ws.S2c) EmitServerMessage(sb, m);
}

static void EmitServerClass(StringBuilder sb, string name, Dictionary<string, string> fields)
{
    sb.AppendLine($"public sealed class {name}");
    sb.AppendLine("{");
    foreach (var (prop, typeSpec) in fields)
    {
        var (type, defVal) = ParseTypeDefault(typeSpec);
        var init = BuildInitializer_Server(type, defVal);
        sb.AppendLine($"  public {type} {prop} {{ get; set; }}{init}");
    }
    sb.AppendLine("}");
}

static void EmitServerMessage(StringBuilder sb, MessageDef m)
{
    sb.AppendLine($"public sealed class {m.Name}");
    sb.AppendLine("{");
    sb.AppendLine($@"  public string Op {{ get; set; }} = ""{m.Op}"";");
    if (m.Fields is not null)
    {
        foreach (var (prop, typeSpec) in m.Fields)
        {
            var (type, defVal) = ParseTypeDefault(typeSpec);
            var init = BuildInitializer_Server(type, defVal);
            sb.AppendLine($"  public {type} {prop} {{ get; set; }}{init}");
        }
    }
    sb.AppendLine("}");
}

static string BuildInitializer_Server(string type, string? defVal)
{
    if (defVal is not null) return $" = {defVal};";
    if (type.StartsWith("string", StringComparison.Ordinal)) return " = string.Empty;";
    if (type.StartsWith("List<", StringComparison.Ordinal)) return $" = new {type}();";
    // 커스텀 참조형 (nullable 아님, 원시형 아님) → new Type() 해서 CS8618 방지
    if (IsNonNullableRef(type)) return $" = new {type}();";
    return "";
}

static bool IsNonNullableRef(string type)
{
    if (type.EndsWith("?")) return false;
    if (type.StartsWith("string") || type.StartsWith("List<")) return false;

    var t = type.TrimEnd('?');
    switch (t)
    {
        case "int":
        case "long":
        case "bool":
        case "double":
        case "float":
        case "decimal":
        case "int?":
        case "long?":
        case "bool?":
        case "double?":
        case "float?":
        case "decimal?":
            return false;
    }
    return char.IsUpper(t[0]); // 대문자 시작이면 DTO라고 가정
}

// ===================== 유니티 방출 (JsonUtility + 필드(camelCase) + 배열) =====================

static void EmitWireJson_Unity(StringBuilder sb)
{
    sb.AppendLine(@"
public static class WireJson
{
    public static string Serialize<T>(T v) => JsonUtility.ToJson(v);
    public static T Deserialize<T>(string json) => JsonUtility.FromJson<T>(json);
}
");
}

static void EmitHttpTypes_Unity(StringBuilder sb, Schema s)
{
    if (s.Http?.Types is null) return;
    foreach (var (name, fields) in s.Http.Types)
        EmitUnityClass(sb, name, fields);
}

static void EmitWsTypes_Unity(StringBuilder sb, Schema s)
{
    if (s.Ws?.Types is null) return;
    foreach (var (name, fields) in s.Ws.Types)
        EmitUnityClass(sb, name, fields);
}

static void EmitWsMessages_Unity(StringBuilder sb, Schema s)
{
    sb.AppendLine("[Serializable] public sealed class OpOnly { public string op = \"\"; }");
    if (s.Ws?.C2s is not null)
        foreach (var m in s.Ws.C2s) EmitUnityMessage(sb, m);
    if (s.Ws?.S2c is not null)
        foreach (var m in s.Ws.S2c) EmitUnityMessage(sb, m);
}

static void EmitUnityClass(StringBuilder sb, string name, Dictionary<string, string> fields)
{
    sb.AppendLine("[Serializable]");
    sb.AppendLine($"public sealed class {name}");
    sb.AppendLine("{");
    foreach (var (prop, typeSpec) in fields)
    {
        var (type, defVal) = ParseTypeDefault(typeSpec);
        var fType = ToUnityFieldType(type); // List<T> -> T[]
        var fName = ToCamel(prop);          // PascalCase -> camelCase
        var init = UnityFieldInitializer(fType, defVal);
        sb.AppendLine($"  public {fType} {fName}{init}");
    }
    sb.AppendLine("}");
}

static void EmitUnityMessage(StringBuilder sb, MessageDef m)
{
    sb.AppendLine("[Serializable]");
    sb.AppendLine($"public sealed class {m.Name}");
    sb.AppendLine("{");
    sb.AppendLine($@"  public string op = ""{m.Op}"";");
    if (m.Fields is not null)
    {
        foreach (var (prop, typeSpec) in m.Fields)
        {
            var (type, defVal) = ParseTypeDefault(typeSpec);
            var fType = ToUnityFieldType(type);
            var fName = ToCamel(prop);
            var init = UnityFieldInitializer(fType, defVal);
            sb.AppendLine($"  public {fType} {fName}{init}");
        }
    }
    sb.AppendLine("}");
}

static string ToUnityFieldType(string type)
{
    if (type.StartsWith("List<", StringComparison.Ordinal))
    {
        var elem = type.Substring(5, type.Length - 6); // List<...>
        return $"{elem}[]";
    }
    return type;
}

static string UnityFieldInitializer(string type, string? defVal)
{
    if (defVal is not null) return $" = {defVal};";
    if (type.StartsWith("string", StringComparison.Ordinal)) return " = \"\";";
    if (type.EndsWith("[]", StringComparison.Ordinal))
    {
        var elem = type[..^2];
        return $" = System.Array.Empty<{elem}>();";
    }
    // 커스텀 참조형 등은 기본값 유지(null). JsonUtility는 누락 필드 허용.
    return ";";
}

static string ToCamel(string name)
{
    if (string.IsNullOrEmpty(name) || char.IsLower(name[0])) return name;
    if (name.Length == 1) return name.ToLowerInvariant();

    // 앞부분이 연속 대문자(약어)인 경우를 처리: "GSAddress" -> "gsAddress", "URL" -> "url", "HTTPRequest" -> "httpRequest"
    int i = 0;
    while (i < name.Length && char.IsUpper(name[i])) i++;

    if (i > 1) // 약어 길이 2 이상
    {
        // 약어 바로 뒤 문자가 소문자면, 약어의 마지막 글자 직전까지만 소문자로 내림
        // 예) "GSAddress": run=3("GSA"), 다음 'd'가 소문자 → "gs" + "Address" = "gsAddress"
        if (i < name.Length && char.IsLower(name[i]))
        {
            var head = name[..(i - 1)].ToLowerInvariant();
            var rest = name[(i - 1)..];
            return head + rest;
        }
        // 전부 대문자거나 뒤도 대문자면 약어 전체를 소문자로
        // 예) "URL" -> "url", "HTTPResponse" (run=4, 뒤 'R'도 대문자) -> "httpResponse"
        return name[..i].ToLowerInvariant() + name[i..];
    }

    // 일반 케이스
    return char.ToLowerInvariant(name[0]) + name[1..];
}

// ===================== 공통: 타입/기본값 파싱 & 스키마 모델 =====================

static (string type, string? defVal) ParseTypeDefault(string spec)
{
    // 예: "string", "int", "long", "bool", "List<RoomDto>", "string?", "int = 2"
    var parts = spec.Split('=', 2, StringSplitOptions.TrimEntries);
    var type = parts[0].Trim();
    string? def = parts.Length == 2 ? parts[1].Trim() : null;

    // 문자열 기본값 따옴표 보정
    if (def is not null && type.StartsWith("string", StringComparison.Ordinal))
        def = $"\"{def.Trim('\"')}\"";
    if (def is not null && type.Equals("bool", StringComparison.Ordinal))
        def = def.ToLowerInvariant();

    return (type, def);
}

// ----- 스키마 모델 -----
public sealed class Schema
{
    public string? Namespace { get; set; }
    public HttpSection? Http { get; set; }
    public WsSection? Ws { get; set; }
}
public sealed class HttpSection
{
    public Dictionary<string, Dictionary<string, string>>? Types { get; set; }
}
public sealed class WsSection
{
    public Dictionary<string, Dictionary<string, string>>? Types { get; set; }
    public List<MessageDef>? C2s { get; set; }
    public List<MessageDef>? S2c { get; set; }
}
public sealed class MessageDef
{
    public string Name { get; set; } = "";
    public string Op { get; set; } = "";
    public Dictionary<string, string>? Fields { get; set; }
}
