// <auto-generated /> DO NOT EDIT (UNITY)
using System;
using UnityEngine;

namespace Contracts.Packet
{

public static class WireJson
{
    public static string Serialize<T>(T v) => JsonUtility.ToJson(v);
    public static T Deserialize<T>(string json) => JsonUtility.FromJson<T>(json);
}

[Serializable]
public sealed class GoogleTokenResponse
{
  public string accessToken = "";
  public string idToken = "";
  public string refreshToken = "";
  public int expiresIn;
  public string tokenType = "";
  public string scope = "";
}
[Serializable]
public sealed class GoogleUserInfo
{
  public string sub = "";
  public string email = "";
  public string name = "";
}
[Serializable]
public sealed class GuestLoginReq
{
  public string deviceId = "";
}
[Serializable]
public sealed class GoogleLoginReq
{
  public string googleSub = "";
}
[Serializable]
public sealed class GoogleLoginRes
{
  public string googleUrl = "";
}
[Serializable]
public sealed class LoginRes
{
  public string uid = "";
  public string accessToken = "";
  public string refreshToken = "";
  public long refreshExpiresAt;
  public long accessExpiresAt;
  public GoogleUserInfo user;
}
[Serializable]
public sealed class RefreshReq
{
  public string refreshToken = "";
}
[Serializable]
public sealed class RefreshRes
{
  public string accessToken = "";
  public string refreshToken = "";
  public long accessExpiresAt;
}
[Serializable]
public sealed class RoomDto
{
  public string id = "";
  public string title = "";
  public string map = "";
  public int max;
  public int cur;
  public string status = "";
  public string visibility = "";
  public long updatedAtMs;
}
[Serializable]
public sealed class CreateRoomReq
{
  public string title = "";
  public string map = "";
  public int max = 2;
  public string visibility = "Public";
}
[Serializable]
public sealed class GetRoomsRes
{
  public RoomDto[] rooms = System.Array.Empty<RoomDto>();
  public string nextCursor = "";
  public long serverTimeMs;
  public string version = "";
}
[Serializable]
public sealed class CreateRoomRes
{
  public string roomId = "";
  public string wsUrl = "";
  public string token = "";
}
[Serializable]
public sealed class JoinRoomRes
{
  public string wsUrl = "";
  public string token = "";
  public RoomDto room;
}
[Serializable]
public sealed class ErrorRes
{
  public string error = "";
  public string message = "";
  public string traceId = "";
}
[Serializable]
public sealed class MemberDto
{
  public string userId = "";
  public string name = "";
  public int slot;
  public bool ready;
}
[Serializable]
public sealed class CountdownDto
{
  public int seconds;
  public long startAtMs;
}
[Serializable]
public sealed class WelcomeState
{
  public RoomDto room;
  public MemberDto[] members = System.Array.Empty<MemberDto>();
  public CountdownDto countdown;
}
[Serializable]
public sealed class RoomPatch
{
  public int cur;
  public string status = "";
  public long updatedAtMs;
}
[Serializable]
public sealed class GameServerDto
{
  public string host = "";
  public int port;
}
[Serializable] public sealed class OpOnly { public string op = ""; }
[Serializable]
public sealed class HelloMsg
{
  public string op = "hello";
  public string token = "";
  public string version = "";
}
[Serializable]
public sealed class ReadyMsg
{
  public string op = "ready";
  public bool value;
}
[Serializable]
public sealed class LeaveMsg
{
  public string op = "leave";
}
[Serializable]
public sealed class WelcomeMsg
{
  public string op = "welcome";
  public WelcomeState state;
  public long serverTimeMs;
}
[Serializable]
public sealed class MemberJoinMsg
{
  public string op = "member.join";
  public MemberDto member;
}
[Serializable]
public sealed class MemberLeaveMsg
{
  public string op = "member.leave";
  public string id = "";
}
[Serializable]
public sealed class MemberUpdateMsg
{
  public string op = "member.update";
  public string id = "";
  public bool ready;
}
[Serializable]
public sealed class RoomUpdateMsg
{
  public string op = "room.update";
  public RoomPatch patch;
}
[Serializable]
public sealed class CountdownStartMsg
{
  public string op = "countdown.start";
  public int seconds;
  public long startAtMs;
}
[Serializable]
public sealed class CountdownCancelMsg
{
  public string op = "countdown.cancel";
}
[Serializable]
public sealed class GameBeginMsg
{
  public string op = "game.begin";
  public GameServerDto gsAddress;
  public string ticket = "";
  public int protoVer;
}
[Serializable]
public sealed class WarnMsg
{
  public string op = "warn";
  public string code = "";
  public string target = "";
  public int perSec;
}
}
